compile_pdf:
  # image: blang/latex
  # This image includes Inkscape but is old
  # image: cwpearson/latex:full
  # This image fails with Inkscape
  # aergus/latex
  image: agenttix/latex:latest
  script:
    # Allow exit code 2
    - make  # || [ $? -eq 2 ]
    - mv "main.pdf" "MSc thesis 2 Mika Mäki.pdf"
  artifacts:
    paths:
      - "MSc thesis 2 Mika Mäki.pdf"
